---

- hosts: all

  vars:
    localip: "{{ ansible_facts.eth0.ipv4.address }}"

  tasks:
  - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  - name: Install Net Tools
    yum:
      name: net-tools
      state: latest

  - name: Add repository
    yum_repository:
     name: influxdbrepo
     description: influxdb YUM repo
     baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
     enabled: 1
     gpgcheck: yes
     gpgkey: https://repos.influxdata.com/influxdb.key

  - name: Install InfluxDB server
    yum:
     name: influxdb
     state: latest

  - name: Update all packages
    yum:
      name: "*"
      state: latest

  - name: Install Epel Repo
    yum:
      name: epel-release
      state: latest

  - name: Install Python PIP
    yum:
      name: python-pip
      state: latest

  - name: PIP and influxdb
    command: "pip install influxdb"

  - name: Enable service
    service:
     name: influxdb
     state: started
     enabled: yes


  - name: Create Database
    influxdb_database:
      hostname: "localhost"
      database_name: "raspberry"
      state: present


  - name: "[Centos7_InfluxDB] Create InfluxDB user"
    command: 'influx -database {{item.database}} -execute "CREATE USER {{item.user}} WITH PASSWORD
             {{item.pass}} WITH ALL PRIVILEGES"'
    with_items:
      - { database: "raspberry", user: "raspuser", pass: "'rasppass'" }

  - name: Add Grafana repository
    yum_repository:
      name: grafanarepo
      description: Grafana YUM repo
      baseurl: https://packagecloud.io/grafana/stable/el/7/$basearch
      enabled: 1
      gpgcheck: yes
      gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

  - name: Install Grafana
    yum:
      name: grafana
      state: latest

  - name: Enable Grafana service
    service:
      name: grafana-server
      state: started
      enabled: yes

  - name: Create Grafana datasource
    grafana_datasource:
      name: influxdb
      grafana_url: http://localhost:3000
      ds_type: influxdb
      database: raspberry
      url: http://localhost:8086
      basic_auth_user: raspuser
      basic_auth_password: rasppass
      state: present
